---
- name: working
  hosts: prod
  tasks:
    - name: test
      command: curl http://169.254.169.254/latest/meta-data/public-ipv4
      register: output
    - set_fact: variable="{{output.stdout}}"
      register: test
    - debug: msg="{{test}}"
