---
- name: working with hostvars
  hosts: prod
  tasks:
   - name: working with when ==
     command: echo "{{ansible_distribution}}"
     when: (ansible_os_family == "RedHat")
   - name: working with when and
     command: echo "{{ansible_distribution}}"
     when: (ansible_os_family == "RedHat") or (ansible_distribution == "Amaon")
   - name: working with when using relational operations
     command: echo "{{value}}"
     when: ( {{value}} <= 4)
     ignore_errors: True
   - name: working with when using define
     command: echo "Its undefined"
     when: (value is undefined)
    
